"""
Reply Builder — Phase 6 Utility
Builds formatted outgoing email bodies for all agent response types.
All replies include the mandatory AI disclaimer footer.
"""

DISCLAIMER = "\n\n---\nThis email was sent by an experimental AI assistant."


def build_confirmation_email(slot: dict, event_link: str, participants: list[str]) -> str:
    """
    Build a meeting confirmation email body.

    Args:
        slot: dict with keys 'date', 'start', 'end', 'timezone'
        event_link: Google Calendar HTML event link
        participants: list of attendee emails
    """
    date = slot.get("date", "TBD")
    start = slot.get("start", "TBD")
    end = slot.get("end", "TBD")
    tz = slot.get("timezone", "UTC")
    attendees = ", ".join(participants) if participants else "you"

    body = (
        f"Great news! I have automatically scheduled the meeting for you.\n\n"
        f"📅 Date      : {date}\n"
        f"⏰ Time      : {start} – {end} {tz}\n"
        f"👥 Attendees : {attendees}\n\n"
        f"You can view, edit, or cancel the event here:\n"
        f"🔗 {event_link}\n\n"
        f"A Google Calendar invite with a Google Meet link has been sent to all attendees."
    )
    return body + DISCLAIMER


def build_clarification_email(question: str) -> str:
    """
    Build a polite clarification request email body.

    Args:
        question: The specific question generated by the LLM to resolve ambiguity.
    """
    body = (
        f"Thank you for reaching out!\n\n"
        f"I noticed your email mentions scheduling, but I need a bit more detail "
        f"to book the meeting correctly:\n\n"
        f"{question}\n\n"
        f"Once I have this information, I will automatically schedule the meeting "
        f"and send calendar invitations to all parties."
    )
    return body + DISCLAIMER


def build_summary_email(summary: str) -> str:
    """
    Build a thread summary / status update email body.

    Args:
        summary: 2–3 sentence summary of the email thread generated by the LLM.
    """
    body = (
        f"Here is a brief summary of the current status based on this email thread:\n\n"
        f"{summary}\n\n"
        f"If you need any further action, please reply and I will assist you."
    )
    return body + DISCLAIMER


def build_generic_acknowledgement() -> str:
    """
    Build a generic acknowledgement for unrecognised or 'unknown' intent emails.
    """
    body = (
        "Thank you for your email. I have received your message and "
        "a human operator will follow up with you shortly."
    )
    return body + DISCLAIMER
